#!/usr/bin/env bash
# GitHub Pages 用の site/ を組み立てる。build_reference.py を先に実行しておくこと。
# Makefile（ローカルプレビュー）と .github/workflows/publish.yml の両方から呼ぶ。
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SITE="${1:-$ROOT/site}"

# 誤削除防止: 既存の SITE は空か、このスクリプトが書いた生成マーカー付き _config.yml があるときだけ消す
MARKER='# generated by scripts/build_site.sh — do not edit'
if [ -d "$SITE" ] && [ -n "$(ls -A "$SITE")" ] && ! grep -qF -- "$MARKER" "$SITE/_config.yml" 2>/dev/null; then
  echo "中止: $SITE は build_site.sh の生成物ではないので削除しない" >&2
  exit 1
fi
rm -rf "$SITE"
mkdir -p "$SITE"
cp "$ROOT/README.md" "$ROOT/llms.txt" "$ROOT/LICENSE" "$ROOT/LICENSE-CONTENT" "$SITE/"
[ -d "$ROOT/docs" ] && cp -r "$ROOT/docs" "$SITE/docs"
cp -r "$ROOT/reference" "$SITE/reference"

for lang in typescript python go csharp cpp react ruby rust sql; do
  if [ -d "$ROOT/$lang/cards" ]; then
    mkdir -p "$SITE/$lang"
    cp -r "$ROOT/$lang/cards" "$SITE/$lang/cards"
    [ -f "$ROOT/$lang/SKILL.md" ] && cp "$ROOT/$lang/SKILL.md" "$SITE/$lang/"
  fi
done

# Liquid を無効化: カードのコード（Go の {{1, 2}} や JSX）を Liquid の変数・タグと誤認して
# ビルドが落ちるため、各 Markdown の本文を {% raw %} 〜 {% endraw %} で包む（frontmatter は残す）
python3 - "$SITE" <<'PY'
import sys
from pathlib import Path
for md in Path(sys.argv[1]).rglob("*.md"):
    text = md.read_text(encoding="utf-8")
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end < 0:
            continue
        head, body = text[: end + 5], text[end + 5 :]
    else:
        head, body = "", text
    if "{% endraw %}" in body or "{%endraw%}" in body:
        # 本文に閉じタグそのものがあると raw ブロックが途中で終わり Liquid が再び有効になる
        sys.exit(f"{md}: 本文に {{% endraw %}} を含む Markdown は配信できない")
    md.write_text(head + "{% raw %}\n" + body.rstrip("\n") + "\n{% endraw %}\n", encoding="utf-8")
PY

# Jekyll（github-pages gem）の設定。frontmatter の無い .md も HTML 化し、元の .md も残す（llms.txt から参照するため）
{
  echo "$MARKER"
  cat <<'YAML'
title: ai-repertoire
theme: jekyll-theme-primer
markdown: kramdown
optional_front_matter:
  remove_originals: false
include:
  - llms.txt
YAML
} > "$SITE/_config.yml"

echo "site: $SITE"
find "$SITE" -type f | sort
