#!/usr/bin/env python3
"""言語別カード（*/cards/*.md）から機能別リファレンスを生成する。

出力:
  reference/<id>.md   … id ごとの言語横断ページ（対応表 + 言語別の転記）
  reference/index.md  … id × 言語の存在表（領域プレフィックスで節分け）
  llms.txt            … reference/*.md の一覧

純粋関数: group_by_id / render_reference / render_index / render_llms_txt。
ファイル I/O は main() だけ。
"""
from __future__ import annotations

import argparse
import shutil
import sys
from collections import OrderedDict
from pathlib import Path
from typing import Dict, List

sys.path.insert(0, str(Path(__file__).resolve().parent))
from cardlib import LANG_LABEL, LANG_ORDER, Card, lang_sort_key, load_cards, test_path  # noqa: E402

GENERATED_MARK = "<!-- generated by scripts/build_reference.py — do not edit -->"
REFERENCE_SECTIONS = ("Signature", "Usage", "Contract", "Alternatives", "Pitfalls")


def group_by_id(cards: List[Card]) -> "OrderedDict[str, List[Card]]":
    """id ごとに言語の固定順で集約する。id は辞書順"""
    groups: Dict[str, List[Card]] = {}
    for c in cards:
        groups.setdefault(c.id, []).append(c)
    return OrderedDict(
        (cid, sorted(groups[cid], key=lambda c: lang_sort_key(c.lang))) for cid in sorted(groups)
    )


def select_public(cards: List[Card]) -> List[Card]:
    """status: public のカードだけを残す"""
    return [c for c in cards if c.meta.get("status") == "public"]


def _label(lang: str) -> str:
    return LANG_LABEL.get(lang, lang)


def _order_mark(card: Card) -> str:
    v = card.meta.get("preserves_order")
    if v is True:
        return "✓"
    if v is False:
        return "✗"
    return "–"


def _tags(card: Card) -> List[str]:
    return [str(t) for t in card.meta.get("tags", [])]


def render_reference(cards: List[Card]) -> str:
    """同じ id のカード群から reference/<id>.md を作る"""
    if not cards:
        raise ValueError("cards が空")
    cards = sorted(cards, key=lambda c: lang_sort_key(c.lang))
    head = cards[0]
    tags = list(OrderedDict.fromkeys(t for c in cards for t in _tags(c)))

    out = [GENERATED_MARK, "", f"# {head.title}", "", f"ID: `{head.id}`  ", f"タグ: {', '.join(tags)}", ""]
    if head.preamble:
        out += [head.preamble, ""]

    out += ["| 言語 | lib | fn | 順序保持 | verified |", "|---|---|---|---|---|"]
    for c in cards:
        out.append(
            f"| {_label(c.lang)} | {c.meta.get('lib', '')} | `{c.meta.get('fn', '')}` "
            f"| {_order_mark(c)} | {c.meta.get('verified', '未検証')} |"
        )
    out.append("")

    for c in cards:
        out += [f"### {_label(c.lang)}", ""]
        for name in REFERENCE_SECTIONS:
            body = c.section(name)
            if body:
                out += [f"#### {name}", "", body, ""]
        tp = test_path(c)
        if tp:
            out += ["#### Test", "", f"`{c.lang}/{tp}`", ""]
    return "\n".join(out).rstrip() + "\n"


def _prefix(cid: str) -> str:
    return cid.split("-", 1)[0]


def render_index(groups: "OrderedDict[str, List[Card]]") -> str:
    """reference/index.md: id × 言語の存在表。領域プレフィックスで節分け"""
    present = {c.lang for cards in groups.values() for c in cards}
    langs = [l for l in LANG_ORDER if l in present] + sorted(present - set(LANG_ORDER))

    out = [GENERATED_MARK, "", "# Index", "", f"{len(groups)} 件。言語列の ✓ はその言語のカードがあることを示す。", ""]
    header = "| ID | title | " + " | ".join(_label(l) for l in langs) + " |"
    sep = "|---|---|" + "|".join("---" for _ in langs) + "|"

    by_prefix: "OrderedDict[str, List[str]]" = OrderedDict()
    for cid in groups:
        by_prefix.setdefault(_prefix(cid), []).append(cid)

    for prefix, ids in by_prefix.items():
        out += [f"## {prefix}", "", header, sep]
        for cid in ids:
            cards = groups[cid]
            have = {c.lang for c in cards}
            cells = " | ".join("✓" if l in have else "" for l in langs)
            out.append(f"| [{cid}]({cid}.md) | {cards[0].title} | {cells} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_llms_txt(groups: "OrderedDict[str, List[Card]]", base_url: str = "") -> str:
    """llms.txt: reference/*.md を 1 行 1 件で列挙（title と tags を添える）"""
    base = base_url.rstrip("/") + "/" if base_url else ""
    out = [
        GENERATED_MARK,
        "",
        "# ai-repertoire",
        "",
        "> AI コーディング向け「引き出し」カタログ。用途語から既存の関数・ライブラリを引くための機能別リファレンス。",
        "> 1 ページ = 1 機能。各ページに言語ごとの Signature / Usage / Contract がある。",
        "",
        f"- [Index]({base}reference/index.md): 全 ID × 言語の対応表",
        "",
        "## Reference",
        "",
    ]
    for cid, cards in groups.items():
        tags = list(OrderedDict.fromkeys(t for c in cards for t in _tags(c)))
        langs = ", ".join(_label(c.lang) for c in cards)
        out.append(f"- [{cards[0].title}]({base}reference/{cid}.md): {cid} — {', '.join(tags)} ({langs})")
    return "\n".join(out).rstrip() + "\n"


def is_generated_dir(path: Path) -> bool:
    """空か、index.md が生成マーク付きなら生成物ディレクトリとみなす（誤削除防止）"""
    if not any(path.iterdir()):
        return True
    index = path / "index.md"
    if not index.is_file():
        return False
    with index.open(encoding="utf-8") as f:
        return f.readline().strip() == GENERATED_MARK


def main(argv: List[str] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent, help="リポジトリルート")
    parser.add_argument("--out", type=Path, default=None, help="reference/ の出力先（既定: <root>/reference）")
    parser.add_argument("--llms", type=Path, default=None, help="llms.txt の出力先（既定: <root>/llms.txt）")
    parser.add_argument("--base-url", default="", help="llms.txt のリンクに付ける URL（例: https://<user>.github.io/ai-repertoire）")
    parser.add_argument("--public-only", action="store_true", help="status: public のカードだけを生成対象にする（公開配信用）")
    args = parser.parse_args(argv)
    root: Path = args.root
    out_dir: Path = args.out or root / "reference"
    llms_path: Path = args.llms or root / "llms.txt"

    cards = load_cards(root)
    if args.public_only:
        cards = select_public(cards)
    groups = group_by_id(cards)

    if out_dir.exists():
        if not is_generated_dir(out_dir):
            print(f"中止: {out_dir} は build_reference.py の生成物ではないので削除しない", file=sys.stderr)
            return 1
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)
    for cid, cards in groups.items():
        (out_dir / f"{cid}.md").write_text(render_reference(cards), encoding="utf-8")
    (out_dir / "index.md").write_text(render_index(groups), encoding="utf-8")
    llms_path.write_text(render_llms_txt(groups, args.base_url), encoding="utf-8")

    print(f"生成: {out_dir}/ に {len(groups)} 件 + index.md, {llms_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
